// Book 3 Sample Questions — 45 MCQs transcribed from the printed paper.
// `a` is the index of the correct option in `opts`.
const QUESTIONS = [
  { q: "What are furoo-e-deen?", opts: ["The branches of Islam", "Madressa books", "Roots of religion", "Good manners"], a: 0 },
  { q: "What does amr bil maroof mean?", opts: ["Praying five times a day", "Stop others from doing evil", "Good manners", "Guide others to do good"], a: 3 },
  { q: "What does nahy anil munkar mean?", opts: ["Good manners", "Stop others from doing evil", "Guide others to do good", "None of the above"], a: 1 },
  { q: "What do you get gunah (sin) for doing?", opts: ["Doing good deeds", "Being lazy", "Doing a bad deed", "Praying"], a: 2 },
  { q: "What is gunah-e-kabira?", opts: ["Big sins", "Being dirty", "Talking too much", "Small sins"], a: 0 },
  { q: "What is gunah-e-saghira?", opts: ["Big sins", "Being dirty", "Talking too much", "Small sins"], a: 3 },
  { q: "What is taubah?", opts: ["Praying five times a day", "Fasting", "Asking for forgiveness", "Giving money to charity"], a: 2 },
  { q: "Why should we obey Allah?", opts: ["Allah created us to worship Him", "Allah knows what is good for us", "It is for our own benefit", "All of the above"], a: 3 },
  { q: "What is religion?", opts: ["A collection of beliefs", "Doing good deeds", "Praying five times a day", "Good manners"], a: 0 },
  { q: "The teaching of Islam (shariah) consists of", opts: ["Beliefs, characters, social and economic guidance", "Usool-e-deen only", "Furoo-e-deen", "Attending madressa"], a: 0 },
  { q: "What is wajib?", opts: ["Wajib means compulsory, we must do it", "If you do a wajib act you get thawaab (blessings)", "If you do not do a wajib act you get gunnah (sin)", "All of the above"], a: 3 },
  { q: "What is a sunnah act?", opts: ["A wajib act", "A bad deed", "If you do not do a sunnah act you get gunnah", "The actions and sayings of the Prophet and Imams (a.s) which are beneficial for us"], a: 3 },
  { q: "What is makruh?", opts: ["Something you do to get thawaab (blessings)", "Giving money to charity", "An act not liked by Allah but is not haram", "Listening to the teachings of your parents"], a: 2 },
  { q: "What is haram?", opts: ["Acts we must never do", "Acts we should do", "Acts we should try not to do", "None of the above"], a: 0 },
  { q: "What is mubah?", opts: ["An act we must not do", "An act we should try to do", "An act with no gunnah or thawaab", "An act we should avoid"], a: 2 },
  { q: "A person who submits to the will of Allah is a", opts: ["Muslim", "Believer", "Zahid", "Atheist"], a: 0 },
  { q: "A person who says that they are a Muslim but in his heart he does not follow is a", opts: ["Mumin", "Muttaqi", "Mushrik", "Munafiq"], a: 3 },
  { q: "A Muslim who believes in the justice of Allah and the 12 Imams is a", opts: ["Muttaqi", "Mumin", "Zahid", "Mushrik"], a: 1 },
  { q: "A person who does not like the things of this world is a", opts: ["Muslim", "Munafiq", "Zahid", "Mushrik"], a: 2 },
  { q: "A person who is pious is a", opts: ["Muttaqi", "Kafir", "Fassiq", "Munafiq"], a: 0 },
  { q: "A person who is not a Muslim is a", opts: ["Fassiq", "Munafiq", "Zahid", "Kafir"], a: 3 },
  { q: "A person who believes that Allah has a partner is a", opts: ["Mushrik", "Fassiq", "Kafir", "Munafiq"], a: 0 },
  { q: "Wudu is wajib (required) for", opts: ["Salah", "Entering mosque", "Visiting graveyard", "All of the above"], a: 0 },
  { q: "Which of the following is a condition of wudu?", opts: ["All parts of the body must be tahir", "Water is tahir (pure)", "Enough time available", "All of the above"], a: 3 },
  { q: "Which of the following is a wajib action of wudhu?", opts: ["Niyyah", "Wash hands", "Wash nose", "Gargle"], a: 0 },
  { q: "What makes wudhu batil?", opts: ["Eating", "Sleeping", "Drinking", "None of the above"], a: 1 },
  { q: "What does <i>hayya alas salah</i> mean?", opts: ["Rush to success", "Rush to best act", "Rush to prayer", "The prayer has begun"], a: 2 },
  { q: "What does <i>hayya ala khairil amal</i> mean?", opts: ["Rush to good deed", "Rush to best act", "Rush to prayer", "The prayer has begun"], a: 0 },
  { q: "What does <i>hayya alal falah</i> mean?", opts: ["Rush to success", "Rush to best act", "Rush to prayer", "The prayer has begun"], a: 0 },
  { q: "What does <i>qad qamatis salah</i> mean?", opts: ["Rush to success", "Rush to best act", "Rush to prayer", "The prayer has begun"], a: 3 },
  { q: "When does fajr salah start?", opts: ["At sunrise", "After midnight", "From true dawn", "After sunrise"], a: 2 },
  { q: "When does dhurain salah start?", opts: ["From midday", "After sunrise", "From dawn", "After sunset"], a: 0 },
  { q: "When does maghribain salah start?", opts: ["After midday", "At midnight", "After sunset", "After midnight"], a: 2 },
  { q: "The clothes for salat must be", opts: ["Tahir", "Mubah", "Made from any part of a halal animal", "All of the above"], a: 3 },
  { q: "Zakat is wajib for those who earn their living from", opts: ["Agriculture / gold &amp; silver / cow, goats &amp; camel", "End of year saving", "Pearls", "Any type of business"], a: 0 },
  { q: "Khums is paid on", opts: ["Saving at the end of the year", "Mining income", "Pearls", "All of the above"], a: 3 },
  { q: "What is the percentage of khums?", opts: ["20%", "25%", "10%", "2.5%"], a: 0 },
  { q: "What does amr-bil-maroof mean?", opts: ["Pray five times a day", "Guide others to do good", "Having good manners", "All of the above"], a: 1 },
  { q: "Hajj is a wajib act and has to be performed ....... in a lifetime", opts: ["As much as possible", "Once", "Twice", "Four times"], a: 1 },
  { q: "Hajj-e-tamattu is performed from the 9th to the 13th of which month?", opts: ["Ramadhan", "Muharram", "Rajab", "Zil Hajj"], a: 3 },
  { q: "The Holy Prophet (pbuh) said &ldquo;I have been sent by Allah to teach people .....&rdquo;", opts: ["Furoo-e-deen", "Good manners", "Usool-e-deen", "Quran"], a: 1 },
  { q: "What does <i>salamun alaykum</i> mean?", opts: ["Hello", "Good morning", "Peace be upon you", "How are you"], a: 2 },
  { q: "What does <i>fi amanillah</i> mean?", opts: ["I leave you in the care of Allah", "Peace be upon you", "May Allah reward you", "None of the above"], a: 0 },
  { q: "Which of these are good manners in the mosque?", opts: ["Enter with your right foot", "Remove your shoes before entering", "Listen carefully", "All of the above"], a: 3 },
  { q: "Which of the following is a good classroom manner?", opts: ["Listen carefully to the teacher", "Talk in the class", "Shout out the answers", "Come late to class"], a: 0 },
];
